name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]  # Python versions to test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Install distutils (needed for some Python packages)
    - name: Install distutils
      run: |
        sudo apt-get update
        sudo apt-get install python3-distutils

    # Step 4: Set up and activate virtual environment (Optional but recommended)
    - name: Set up virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    # Step 2: Install dependencies
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5 (optional): Run tests (if you have tests)
    - name: Run tests
      run: |
        pytest  # Adjust based on your test framework
