name: Python CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'   # Ensure Python version matches your environment

    - name: Install distutils and other essential build tools
      run: |
        sudo apt-get update
        sudo apt-get install python3-distutils python3-dev build-essential -y

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add any test command here if you have tests, for now just run streamlit and others
        python -c "import pandas; import numpy; import sklearn; import matplotlib; import seaborn; import streamlit"
