name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v2

    # Step 2: Set up Python 3.12.4
    - name: Set up Python 3.12.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.4

    # Step 3: Set up and activate virtual environment
    - name: Set up virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    # Step 4: Upgrade pip and install dependencies
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5 (optional): Run tests (if you have tests)
    - name: Run tests
      run: |
        source venv/bin/activate
        pytest  # Adjust based on your test framework
